### PR TITLE
Fix subscription stress test in notifier

### LINKED ISSUE #268: Intermittent test failure: `TestNotifier/MultipleSubscribersStress`
Not super common, but I've seen it a couple times so far.

```
--- FAIL: TestNotifier (0.00s)
    --- FAIL: TestNotifier/MultipleSubscribersStress (0.25s)
        logger.go:[22](https://github.com/riverqueue/river/actions/runs/8257741142/job/22588819288?pr=258#step:8:23)5: time=20[24](https://github.com/riverqueue/river/actions/runs/8257741142/job/22588819288?pr=258#step:8:25)-03-13T00:59:07.700Z level=INFO msg="Notifier: Listener connecting"
        logger.go:225: time=2024-03-13T00:59:07.700Z level=INFO msg="Notifier: Run loop started"
        logger.go:2[25](https://github.com/riverqueue/river/actions/runs/8257741142/job/22588819288?pr=258#step:8:26): time=2024-03-13T00:59:07.700Z level=INFO msg="Notifier: Notifier healthy"
        notifier_test.go:425: Sending notification on "test_topic1": msg0
        logger.go:225: time=2024-03-13T00:59:07.701Z level=INFO msg="Notifier: Listening on topic" topic=test_topic1
        notifier_test.go:425: Sending notification on "test_topic1": msg1
        logger.go:225: time=2024-03-13T00:59:07.892Z level=INFO msg="Notifier: Unlistening on topic" topic=test_topic1
        logger.go:225: time=2024-03-13T00:59:07.892Z level=INFO msg="Notifier: Listener closing"
        logger.go:225: time=2024-03-13T00:59:07.893Z level=INFO msg="Notifier: Run loop stopped"
        notifier_test.go:462: Channel  0 contains   2 message(s)
        notifier_test.go:462: Channel  1 contains   2 message(s)
        notifier_test.go:462: Channel  2 contains   2 message(s)
        notifier_test.go:462: Channel  3 contains   2 message(s)
        notifier_test.go:462: Channel  4 contains   2 message(s)
        notifier_test.go:462: Channel  5 contains   2 message(s)
        notifier_test.go:462: Channel  6 contains   2 message(s)
        notifier_test.go:462: Channel  7 contains   0 message(s)
        notifier_test.go:467: 
            	Error Trace:	/home/runner/work/river/river/internal/notifier/notifier_test.go:467
            	Error:      	Should NOT be empty, but was 0xc000[29](https://github.com/riverqueue/river/actions/runs/8257741142/job/22588819288?pr=258#step:8:30)11[40](https://github.com/riverqueue/river/actions/runs/8257741142/job/22588819288?pr=258#step:8:41)
            	Test:       	TestNotifier/MultipleSubscribersStress
FAIL
```

https://github.com/riverqueue/river/actions/runs/8257741142/job/22588819288

### PR DESCRIPTION
**Pull request by brandur**
While I was trying to fix another problem in the notifier's subscription
stress test, I ended up introducing another one by using a single wait
group for both the notification sending goroutine and subscriptions
loops which caused the test intermittency described in #268. The test
was ending too soon, and channels would only receive 1-2 messages, and
sometimes zero (which would fail the test).

    notifier_test.go:462: Channel  0 contains   2 message(s)
    notifier_test.go:462: Channel  1 contains   2 message(s)
    notifier_test.go:462: Channel  2 contains   2 message(s)
    notifier_test.go:462: Channel  3 contains   2 message(s)
    notifier_test.go:462: Channel  4 contains   2 message(s)
    notifier_test.go:462: Channel  5 contains   2 message(s)
    notifier_test.go:462: Channel  6 contains   2 message(s)
    notifier_test.go:462: Channel  7 contains   0 message(s)

Here, fix the problem by putting in different symbols for the
notification send and subscription loops. The proper order of operations
to finish the test are:

1. Wait for all subscription groups to finish.
2. Tell the notification send loop to shut down.
3. Wait for the notification send loop to return (so as not to introduce
   any goroutine leaks like had been present before).

Fixes #268.

### CODE REVIEW

File: internal/notifier/notifier_test.go [hunk 1]
```diff
@@ -454,9 +455,9 @@ func TestNotifier(t *testing.T) {
 			}()
 		}
 
-		close(shutdown)
-		wg.Wait()
-		notifier.Stop()
```
Comment (brandur) [inline internal/notifier/notifier_test.go:459]: Notifier was already stopping in a `t.Cleanup` above, so this invocation wasn't necessary.

**Review by bgentry — APPROVED** [review]

**Comment by brandur** [comment]
ty.
