### PR TITLE
Definitively fix race in periodic job enqueuer

### LINKED ISSUE #409: Intermittently failing test: `TestPeriodicJobEnqueuer/AddAfterStart`
```
--- FAIL: TestPeriodicJobEnqueuer (0.00s)
    --- FAIL: TestPeriodicJobEnqueuer/AddAfterStart (0.10s)
        periodic_job_enqueuer_test.go:373: 
            	Error Trace:	/home/runner/work/river/river/internal/maintenance/periodic_job_enqueuer_test.go:87
            	            				/home/runner/work/river/river/internal/maintenance/periodic_job_enqueuer_test.go:373
            	Error:      	"[0xc0005bf560 0xc0005bf680]" should have 1 item(s), but has 2
            	Test:       	TestPeriodicJobEnqueuer/AddAfterStart
            	Messages:   	Expected to find exactly 1 job(s) of kind: periodic_job_500ms_start, but found 2
FAIL
```

https://github.com/riverqueue/river/actions/runs/9727144459/job/26846367325?pr=408

### PR DESCRIPTION
**Pull request by brandur**
Related to #409. I think I finally cracked it. For real this time. No
workarounds, no hacks.

If you look at the "after start" tests, they look roughly like this,
start the client, then add some jobs:

    startService(t, svc)

    svc.Add(
        &PeriodicJob{ScheduleFunc: periodicIntervalSchedule(500 * time.Millisecond), ConstructorFunc: jobConstructorFunc("periodic_job_500ms", false)},
    )
    svc.Add(
        &PeriodicJob{ScheduleFunc: periodicIntervalSchedule(500 * time.Millisecond), ConstructorFunc: jobConstructorFunc("periodic_job_500ms_start", false), RunOnStart: true},
    )

This would usually work as expected, with the enqueuer starting up, then
jobs added, then those new jobs scheduled.

_However_, what can happen is that the "after start" jobs are actually
added in _before_ the enqueuer has finished entering its run loop. So,
the service is starting up, makes a first call to `timeUntilNextRun`,
and because the newly added periodic jobs have not been assigned a first
run time, the code below would get a `timerUntilNextRun` of zero, which
would cause it to enter the loop and run an insert iteration
immediately, despite the jobs not actually being appropriate for
scheduling as of yet:

    timerUntilNextRun := time.NewTimer(s.timeUntilNextRun())

    for {
            select {
            case <-timerUntilNextRun.C:

The fix is to modify `timeUntilNextRun` so that it ignores periodic jobs
that have not yet been scheduled:

    for _, periodicJob := range s.periodicJobs {
        // Jobs may have been added after service start, but before this
        // function runs for the first time. They're not scheduled properly yet,
        // but they will be soon, at which point this function will run again.
        // Skip them for now.
        if periodicJob.nextRunAt.IsZero() {
                continue
        }

Those jobs will be scheduled soon, then `timeUntilNextRun` called again,
and the expected "time until" values returned.

I'm confident enough in the fix that I've reverted most of #416 so the
5s jobs go back to 500ms.

Fixes #409.

### CODE REVIEW

File: client_test.go [hunk 1]
```diff
@@ -3956,7 +3956,7 @@ func Test_Client_JobCompletion(t *testing.T) {
 		require.NotNil(updatedJob.FinalizedAt)
 
 		// Make sure the FinalizedAt is approximately ~now:
-		require.WithinDuration(now, *updatedJob.FinalizedAt, time.Second)
+		require.WithinDuration(now, *updatedJob.FinalizedAt, 2*time.Second)
```
Comment (brandur) [inline client_test.go:3959]: Totally unrelated, but one that cropped up as an intermittent failure as I reran this PR's test matrix over and over again. Most duration checks use 2s rather than 1s by convention in this file, so this change makes it match up a little better with other assertions.

**Review by bgentry — APPROVED** [review]
As much as I'm in agreement with GitHub Actions' inconsistent performance, this is bad enough that I'm really becoming convinced there must be something else going on here. This is just an eternity in computer time.

**Comment by brandur** [comment]
Thx. Ugh, yeah you're right that there's definitely something else at work here. I'm going to leave this open and convert it to a draft to help me debug further.

**Comment by brandur** [comment]
@bgentry I think I FINALLY cracked this one. It was a legit bug, although not one that would ever occur IRL probably. I did a complete rewrite of the PR description to describe it. Mind taking another look?

File: internal/maintenance/periodic_job_enqueuer.go [hunk 2]
```diff
@@ -427,14 +428,16 @@ func (s *PeriodicJobEnqueuer) insertParamsFromConstructor(ctx context.Context, c
 	return insertParams, uniqueOpts, true
 }
 
+const periodicJobEnqueurVeryLongDuration = 24 * time.Hour
```
Comment (bgentry) [inline internal/maintenance/periodic_job_enqueuer.go:431]: Small typo in the name of this long constant:

```suggestion
const periodicJobEnqueuerVeryLongDuration = 24 * time.Hour
```

Comment (brandur) [reply internal/maintenance/periodic_job_enqueuer.go]: Oops, thanks. Fixed.
