### PR TITLE
Driver tests for full `lib/pq` connection + necessary fixes

### LINKED ISSUE #545: Elector interval field value out of range
I was evaluating riverqueue for use in one of my projects and after attempting to run it for the first time, I'm getting the following error:

>time=2024-08-21T19:45:12.744Z level=ERROR msg="Elector: Error attempting to elect" client_id=5e589f722171_2024_08_21T19_45_11_805369 err="pq: interval field value out of range: \"15000000000\"" num_errors=2 sleep_duration=1.917471608s

Postgres logs:

> 2024-08-21 19:07:10.854 UTC [70] ERROR:  interval field value out of range: "15000000000"
>  2024-08-21 19:07:10.854 UTC [70] CONTEXT:  unnamed portal parameter $2 = '...'
>  2024-08-21 19:07:10.854 UTC [70] STATEMENT:  -- name: LeaderAttemptElect :execrows
>        INSERT INTO river_leader(leader_id, elected_at, expires_at)
>            VALUES ($1, now(), now() + $2::interval)
>        ON CONFLICT (name)
>            DO NOTHING

I have validated that my migrations worked correctly.

Postgres v14.6 (I'm locked to this version at the moment)
Go v1.23.0
River v0.11.4

Any suggestions?

### PR DESCRIPTION
**Pull request by brandur**
So it turns out that while bearing some relation to `lib/pq` through
various pieces that sqlc pulls in, the `riverdatabasesql` driver didn't
actually work when used with `lib/pq`. When testing it, we'd open a
`sql.DB` pool _via_ Pgx, so Pgx was doing all the heavy lifting.

Here, add an alternate driver test strategy to test `riverdatabasesql`
with a `lib/pq` pool, thereby ensuring that the full range of operations
works even with no Pgx in the mix at all.

Things were broken, so we get those fixed up. There we two main
problems:

* As described in #545, `lib/pq` doesn't handle intervals correctly, and
  reads them in as ints, which is a big problem because they're in
  nanoseconds. We work around this by injecting intervals (like leader
  TTLs) an second floats instead, which really doesn't feel that much
  worse.

* The custom bits class for `unique_states` didn't work. To fix this I
  move to an alternate strategy of inserts `unique_states` as an
  integer, a technique that I've been using in SQLite because there's no
  `bits` type. I could make a strong argument that the use of an integer
  over `bits` would've been a better design from the get go anyway,
  because it makes all the bit-wise arithmetic much simpler as you use
  C-style conventions like `states & (1 << 3)` that are very widespread
  and well understood. Either way though, things work reasonably well if
  we insert as an integer, then transition to storage in bits.

Fixes #545 and #566. Supersedes #882.

### CODE REVIEW

**Comment by brandur** [comment]
@bgentry Mind taking a look at this one?

File: riverdriver/riverpgxv5/internal/dbsqlc/river_leader.sql [hunk 1]
```diff
@@ -9,16 +9,17 @@ CREATE UNLOGGED TABLE river_leader(
 
 -- name: LeaderAttemptElect :execrows
 INSERT INTO /* TEMPLATE: schema */river_leader (leader_id, elected_at, expires_at)
-    VALUES (@leader_id, coalesce(sqlc.narg('now')::timestamptz, now()), coalesce(sqlc.narg('now')::timestamptz, now()) + @ttl::interval)
+    -- @ttl is inserted as
```
Comment (bgentry) [inline riverdriver/riverpgxv5/internal/dbsqlc/river_leader.sql:12]: not sure what this comment is meant to convey

File: riverdriver/riverdatabasesql/river_database_sql_driver.go [hunk 2]
```diff
@@ -999,6 +994,18 @@ func (w templateReplaceWrapper) QueryRowContext(ctx context.Context, sql string,
 	return w.dbtx.QueryRowContext(ctx, sql, args...)
 }
 
+// lib/pq reads in `bits` (like `bits(8)`) as a bit string that's a normal
+// decimal integer like 1111_1111 (_not_ 0b1111_1111). This function converts it
+// back to binary representation. See the test suite for examples.
```
Comment (bgentry) [inline riverdriver/riverdatabasesql/river_database_sql_driver.go:999]: pq 🤦‍♂️

**Review by bgentry — APPROVED** [review]
It's always a bit unfortunate to have to move more in the direction of the lowest common denominator between drivers, but it's tolerable here. In the event we ever need to add another job state it might we'll need more than 8 bits and will need to adjust the approach.

**Comment by philippgille** [comment]
Does this also fix https://github.com/riverqueue/river/issues/566?

**Comment by bgentry** [comment]
@philippgille it should fix it! 🤞

File: riverdriver/riverpgxv5/internal/dbsqlc/river_leader.sql (hunk 1 above)
Comment (brandur) [reply riverdriver/riverpgxv5/internal/dbsqlc/river_leader.sql:12]: Ah doh, I started a comment, but didn't finish it. I just put this more expounded version in instead:

``` sql
-- @ttl is inserted as as seconds rather than a duration because `lib/pq` doesn't support the latter
```

File: riverdriver/riverdatabasesql/river_database_sql_driver.go (hunk 2 above)
Comment (brandur) [reply riverdriver/riverdatabasesql/river_database_sql_driver.go:999]: Yeah haha. There might be some other way around this, but at least this isn't _that_ bad.

**Comment by brandur** [comment]
> It's always a bit unfortunate to have to move more in the direction of the lowest common denominator between drivers, but it's tolerable here.

Yeah for sure.  I was reasonably happy that that none of the hacks to get this working were that gross. Code's different, but not obvious that much worse.

> In the event we ever need to add another job state it might we'll need more than 8 bits and will need to adjust the approach.

Yeah, although most of the integers we're working with are at least four bytes, so they should still mostly work in case we need more than those 8 bits.

**Comment by brandur** [comment]
Thanks!
